import { Drawer } from "@/components/Drawer";
import { Footer } from "@/components/Footer";
import "../styles/globals.css";

export const metadata = {
  title: "Agroturismo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="emerald" lang="pt-br">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
          crossOrigin=""
        />
      </head>
      <body>
        <Drawer>{children}</Drawer>
        <Footer />
      </body>
    </html>
  );
}
