import { Footer } from "@/components/Footer";
import "../styles/globals.css";

export const metadata = {
  title: "Agroturismo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="emerald" lang="pt-br">
      <body>
        {children}

        <Footer />
      </body>
    </html>
  );
}
